version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app/FastAPI_app

    command: uvicorn app.FastAPI_app.main:app --host 127.0.0.1 --port 8000

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_tests
    volumes:
      - .:/app/FastAPI_app

    working_dir: /app/FastAPI_app
    entrypoint: ["pytest", "app/test/test_main.py"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

    
