version: "4"

services: 
  someDB:
    image: someBD:latest
    container_name: amazing.App_db
    environment: #ну это плохо явно
      NAME_DB: "amazing.App_db"
      USER: "skufyari"
      PASSWORD: "S3cR3t14/88"
    volumes:
      - .:/ #неявный путь
    ports:
      - "80:80" #явный порт

  app: 
    build: 
      context: ./ #неявный путь
      dockerfile: Dockerfile 
    command: > #команда которую нужно выполнить
      /bin/sh -c 'some useful command'