name: CI/CD setting with bad practices


on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose

            - name: Build application
              run: docker-compose -f docker-compose.yml up -d --build

            - name: Test application
              run: docker-compose exec FastAPI_app pytest

    deploy:
        needs: test
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose

            - name: Deploy application
              run: |
                  docker-compose -f docker-compose.yml down
                  docker-compose -f docker-compose.yml up -d FastAPI_app