version: "4"

services: 

  someDB:
    image: someBD:latest
    container_name: amazing.App_db
    env_file: 
      - .env.db 
    volumes:
      - DB_data:/var/lib/name_DB/data
    networks:
      - DB_net
    ports:
      - "8080:80"
    restart: always

  app: 
    build:
      context: ./
      dockerfile: Dockerfile 
  depends_on:
      - someDB
  volumes:
      - ./app:/path/to/app
  network:
      - application_net
  command: > 
      /bin/sh 'some useful command'

volumes:
  DB_data:

networks:
  DB_net:
    driver: bridge
  application_net:
    driver: bridge