version: "4"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py  # Четкое определение запускаемого приложения
    command: python3 -m flask run --host=0.0.0.0 --port=5000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge